version: '3'
services:
  flask:
    build: .
    image: leo/flask
    ports:
      - "8080:8080"
    # networks:
    #   - appnet
    # deploy:
    #   mode: replicated
    #   replicas: 1
  gateway:
    build: .
    image: leo/gateway
    ports:
      - "8081:8080"
# networks:
#   appnet:
#     driver: overlay