version: '3.3'

services:
  flask:
    image: leo/flask
    ports:
      - "8080:8080"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
      
  gateway:
    image: leo/gateway
    ports:
      - "8081:8080"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
            - node.role == manager
networks:
  appnet:
    driver: overlay